### ISSUE TITLE
AbML won't render with a connector but will with a linker

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#25]
The following won't render - I drew it and it generated the AbML, but it won't render...
This is a Fab with an appended scFv on the light chain with a normal connection between CL and VH.b

```
VH.a(1:3)-CH1(2:4)|VL.a(3:1)-CL(4:2)-VH.b(5:7)-L(6)-VL.b(7:5)
```

If I change the normal connection to a linker then it renders fine:
```
VH.a(1:3)-CH1(2:4)|VL.a(3:1)-CL(4:2)-L(5)-VH.b(6:8)-L(7)-VL.b(8:6)
```

I think it's fine if we don't allow a normal connection, but we need to have a proper error message rather than a Python error :)

**Comment by JamesSweetJones** [comment]
I've just made a change so whenever there's an issue rendering a domain, a generic error message will pop up. I can work on it so it says something a bit more specific.

**Comment by AndrewCRMartin** [comment]
Also needs an error message to deal with missing domain numbers.
e.g.

```
VH.a(1:3)-CH1(2:4)|VL.a(3:1)-CL(4:2)-L-VH.b(5:7)-L(6)-VL.b(7:5)
```

where I added a linker but didn't include a number for it.

**Comment by JamesSweetJones** [comment]
This has been fixed
