### ISSUE TITLE
Specific ADC site needs to be supported on all domain types

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#28]
```
VL(1:3)-CL^(2:4){1}|VH(3:1)-CH1(4:2){1}-H*(5:12){2}-CH2(6:13)-CH3(7:14)|VL(8:10)-CL^(9:11){1}|VH(10:8)-CH1(11:9){1}-H*(12:5){2}-CH2(13:6)-CH3(14:7)
```
isn't allowed at the moment. INN:12397 has a specific ADC site in CL

**Comment by AndrewCRMartin** [comment]
Actually the `^` modifier never works (and it's not in the interface), but it is in the documentation!!!

**Comment by JamesSweetJones** [comment]
Hi Andrew. "^" is now allowed in the syntax, however I've just noticed there isn't a button for "^" on the keypad. I can fix this relatively easily
