### ISSUE TITLE
miniantibody template

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#29]
I'm not sure why the miniantibody template has a MOD:DISULPHIDE in the hinge - should this be MOD:REMCYS (or perhaps we should add MOD:REMDISULPHIDE) since there seems to be one disulphide instead of the normal 2?

**Comment by JamesSweetJones** [comment]
We can do that if you like. I just put that there because it was in Mahad's original example of miniantibodies.

**Comment by AndrewCRMartin** [comment]
Yes - we didn't have the same set of MOD:s when Mahan did her thesis. I think this should actually be a MOD:REMDISULPHIDE if it only has one disulphide in the hinge.  (and we need to add that to the allowed list in the paper)

**Comment by JamesSweetJones** [comment]
These have been added to the documentation and the list of allowed MOD comments
