### ISSUE TITLE
New challenge - Hinge-Linker

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#30]
INN12138 is a mini-antibody using CH3 instead of a leucine zipper. The AbML is
```
VL(1:3)-L(2)-VH(3:1)-H*(4:10){2}[MOD:REMCYS][NOTE: Nter 5aa extension]-L(5:11){1}-CH3(6:12)|VL(7:9)-L(8)-VH(9:7)-H(10:4){2}[MOD:REMCYS][NOTE: Nter 5aa extension]-L(11:5){1}-CH3(12:6)
```
The hinge includes the last 5 residues of the CH1 and is modified to remove the cys that would normally disulphide with the Cter of the CL is mutated to Cys.

The linker that follows the hinger contains a cysteine to form an extra disulphide with the other chain.

Even if it can't be drawn on the app, it would be good to render it - I guess you could add a H-L (hinge-linker) join type (and a linker-hinge - L-H - at the same time). The H-L would appear as two separate things in the AbML, but a single button on the interface.

Good luck!

**Comment by JamesSweetJones** [comment]
<img width="687" alt="Screenshot 2022-03-15 at 13 51 33" src="https://user-images.githubusercontent.com/73530578/158392535-2f5307bf-76c6-4e7e-80e1-61088c3022c0.png">
Hi Andrew,

Using the second expression you gave, I've come up with this, which can be inputted into abYdraw. Let me know what you think

**Comment by AndrewCRMartin** [comment]
Re-opened since clicking `Get AbML` or `Tidy` doesn't work. But this is **non-urgent**

As mentioned above:

I guess you could 

> You could add a H-L (hinge-linker) join type (and a linker-hinge - L-H - at the same time). The H-L would appear as two separate things in the AbML, but a single button on the interface.

**Comment by JamesSweetJones** [comment]
Think I've cracked it!

James
