### ISSUE TITLE
Another Fc fusion problem with dangling hinge

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#37]
```
X(1)-H(2:5){2}-CH2(3:6)-CH3@(4:7)|H(5:2){2}-CH2(6:3)-CH3>(7)
```
won't render because the initial Hinge of the second chain isn't connected to anything to its N-terminus

**Comment by JamesSweetJones** [comment]
I've made this drawable but still having trouble making the AbML render for it.

**Comment by JamesSweetJones** [comment]
Fixed!
