### ISSUE TITLE
tkinter error

### ISSUE THREAD

**Issue by mkresgil** [JamesSweetJones/abYdraw#40]
when trying to run abydraw, after installing using the install.py

 python3 abYdraw.py
Traceback (most recent call last):
  File "abYdraw.py", line 7628, in <module>
    root = tk.Tk()

it raises this error:
have tried changing import tkinter as Tk, cannot find a file in directory called tkinter.py.

has anyone had this problem or no a solution?

**Comment by JamesSweetJones** [comment]
Hello mkresgil.

I'm afraid I have not had this issue with Tkinter. 
`import tkinter as tk`
Is the usual syntax to import Tkinter and .Tk() is a function within it. May I ask what version of python you are using? 
Potentially you could use this code in your terminal to update your version of Tkinter. 
`pip install tk --upgrade`
Please let me know if this works.

James

**Comment by mkresgil** [comment]
James,

Thank you so much for the quick response. I am using Python 3.6.8. After trying what you mentioned the same error
  File "abYdraw.py", line 7628, in <module>
    root = tk.Tk()
AttributeError: module 'tkinter' has no attribute 'Tk'

Not sure if you have any other advice. I will maybe try installing on another system and see what happens.

Thanks for the help!

McClain

From: James ***@***.***>
Sent: Thursday, July 21, 2022 12:22 AM
To: ***@***.***>
Cc: McClain ***@***.***>; ***@***.***>
Subject: [EXTERNAL] Re: [JamesSweetJones/abYdraw] tkinter error (Issue #40)


Hello mkresgil.

I'm afraid I have not had this issue with Tkinter.
import tkinter as tk
Is the usual syntax to import Tkinter and .Tk() is a function within it. May I ask what version of python you are using?
Potentially you could use this code in your terminal to update your version of Tkinter.
pip install tk --upgrade
Please let me know if this works.

James

**Comment by mkresgil** [comment]
Hello,

the version is 3.6.8, the pip install did not aid in helping. 

I will continue to try and see what happens

**Comment by AndrewCRMartin** [comment]
We have had another report of the same issue on RHEL8. There seems to be a
problem with the tkinter package that comes with Python3 on RHEL8 / CentOS8

A.

**Comment by JamesSweetJones** [comment]
Hello mkres

> Hello,
> 
> the version is 3.6.8, the pip install did not aid in helping.
> 
> I will continue to try and see what happens

Find out which version of tkinter you are running. I am running Version 8.6 which includes the Tk command.
You can find out simply with this code:
`import tkinter
tkinter.TkVersion
`
If you are running an older version, please see these documents to install the newer versions: https://tkdocs.com/tutorial/install.html

Best,
James
