### ISSUE TITLE
scFv-TCR not bringing the TCR chains together properly

### ISSUE THREAD

**Issue by AndrewCRMartin** [JamesSweetJones/abYdraw#44]
```
VL.a(1:3)-L(2)-VH.a(3:1)-L(4)-VB.a(5:7)-CB*(6:8){1}|VA.a(7:5)-CA*(8:6){1}
```

This structure is an scFv(VL-VH) fused via a linker to a TCR beta chain. The beta chain region then pais with an alpha chain with the constant domains having an artificial disulphide.

It renders, but the VB-CB is miles away from the VA-CA

**Comment by JamesSweetJones** [comment]
Solved in latest push
